
package code;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "emailServiceService", targetNamespace = "http://code/", wsdlLocation = "http://localhost:4568/email?wsdl")
public class EmailServiceService
    extends Service
{

    private final static URL EMAILSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EMAILSERVICESERVICE_EXCEPTION;
    private final static QName EMAILSERVICESERVICE_QNAME = new QName("http://code/", "emailServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/emailWeb/services/emailServicePort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMAILSERVICESERVICE_WSDL_LOCATION = url;
        EMAILSERVICESERVICE_EXCEPTION = e;
    }

    public EmailServiceService() {
        super(__getWsdlLocation(), EMAILSERVICESERVICE_QNAME);
    }

    public EmailServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMAILSERVICESERVICE_QNAME, features);
    }

    public EmailServiceService(URL wsdlLocation) {
        super(wsdlLocation, EMAILSERVICESERVICE_QNAME);
    }

    public EmailServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMAILSERVICESERVICE_QNAME, features);
    }

    public EmailServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmailServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmailService
     */
    @WebEndpoint(name = "emailServicePort")
    public EmailService getEmailServicePort() {
        return super.getPort(new QName("http://code/", "emailServicePort"), EmailService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmailService
     */
    @WebEndpoint(name = "emailServicePort")
    public EmailService getEmailServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://code/", "emailServicePort"), EmailService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMAILSERVICESERVICE_EXCEPTION!= null) {
            throw EMAILSERVICESERVICE_EXCEPTION;
        }
        return EMAILSERVICESERVICE_WSDL_LOCATION;
    }

}
